version: '3'
services:
  db:
    container_name: "mypostgres"
    image: "postgres"
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appuser
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - backend-network

  pgadmin4:
    container_name: "mypgadmin4"
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      POSTGRES_HOST_sAUTH_METHOD: trust
    ports:
      - "8000:80"
    networks:
      - backend-network
    depends_on:
      - db
  
  configserver:
    container_name: "configserver"
    image: configserver
    build:
      context: ./configserver
      dockerfile: Dockerfile
    ports:
      - "9095:9095"
    environment:
      spring.\profiles.\active: docker
    networks:
      - backend-network

  register:
    container_name: "register"
    image: register
    build:
      context: ./register
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - pgadmin4
      - db
    environment:
      spring.\profiles.\active: docker
    networks:
      - backend-network

  emailapi:
    container_name: "emailapi"
    image: emailapi
    build:
      context: ./emailapi
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    depends_on:
      - register
    environment:
      spring.\profiles.\active: docker
    networks:
      - backend-network

  userapi:
    container_name: "userapi"
    image: userapi
    build:
      context: ./userapi
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    depends_on:
      - pgadmin4
      - db
      - register
      - configserver
    environment:
      spring.\profiles.\active: docker
    networks:
      - backend-network

  gateway:
    container_name: "gateway"
    image: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - pgadmin4
      - db
      - register
    environment:
      spring.\profiles.\active: docker
    networks:
      - backend-network

networks:
  backend-network: