server:
  port: 9090
  servlet:
    context-path: /register

spring:
  application:
    name: Register
  security:
    user:
      name: admin
      password: 123456

eureka:
  instance:
    hostname: register
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    serviceUrl:
        defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
