server:
  port: 9091

flyway:
  enabled: true
  baseline-on-migrate: true
  validate-on-migrate: true
  locations: classpath:db/migration

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: appuser
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /monitor
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

